### ISSUE TITLE
PHP 7/7.1 Issues with String and Integer concat

### ISSUE THREAD

**Issue by Sladewill** [OpenSRS/osrs-toolkit-php#36] opened 2017-10-20 08:14 UTC
https://github.com/OpenSRS/osrs-toolkit-php/blob/15d2d8c2fbd8edb54d919deba1661cca2a1a4134/opensrs/Ops.php#L196

With this line of code php throws an error, surely this should use the . to combine the variables together.

**Comment by developernaren** [comment] 2018-12-12 07:48
@Sladewill this is giving me issues while upgrading php version. How did you get rid of the issue?

**Comment by Sladewill** [comment] 2018-12-12 12:43
I believe we forked it and used our own private repo.

**Comment by developernaren** [comment] 2018-12-12 14:11
I did same for the moment. But this is really weird. There is even a PR with a change to fix this, but it is not merged. The issue is more than a year old.

**Comment by Sladewill** [comment] 2018-12-13 12:04
I believe the project has been abandoned considering the last activity was April 2017.

**Comment by tracer99** [comment] 2020-08-28 16:46
Tracked in #38

**Closed by tracer99** 2020-08-28 16:46 UTC
Labels: duplicate
